### ISSUE TITLE
Allow configuration of attached LCD Screen

### ISSUE THREAD

**Issue by sarreck** [SuperHouse/OXRS-SHA-Rack32-ESP32-LIB#16]
It would be useful to be able to configure the attached screen with the following options

1. Screen ON/OFF
2. If Screen ON - time before dimming (new action brightens screen and resets dimming timer)
3. If Screen ON - time to turn screen off after dimming  (0 - screen stays on), (new action turns screen on, brightens screen and resets dimming timer)

While the above would be configured by MQTT, perhaps a button to turn the screen on through the WEB UI would be useful.

**Comment by sumnerboy12** [comment]
I think the config schema for this should live in the Rack32 library.

**Comment by moinmoin-sh** [comment]
Agreed.

The LCD api is ready (PR issued). I assume that you integrate the config option into the json schema
