### ISSUE TITLE
Temperatur display at start up

### ISSUE THREAD

**Issue by moinmoin-sh** [SuperHouse/OXRS-SHA-Rack32-ESP32-LIB#41]
show the temperature on display imediately after start up.
optimise hide/unhide temperature display depending on async config changes

**Comment by moinmoin-sh** [comment]
Proposed solution for :
 > optimise hide/unhide temperature display depending on async config changes

additional function in LCD-lib :  `OXRS_LCD::hideTemp(void) `
this wipes the `TEMP: ... ` line but doesn't touch `_yTemp`.
subsequent calls of `OXRS_LCD::showTemp()` will again display the `TEMP: ...`  line at the stored `_yTemp `position as before.

`OXRS_LCD::setTEMPpos()` stays as is and works as intended setup function


>

**Comment by sumnerboy12** [comment]
Could we just modify `showTemp()` so that if you pass `NAN` it hides the temp? Then no change to the LCD library and if temp reporting is disabled, the firmware (or Rack32 lib) just sends `screen.showTemp(NAN)`?

**Comment by moinmoin-sh** [comment]
This wouldn't work without a change to the LCD lib , but it doesn't add a new member.

We can go that path if you prefer. I'll prepare the change.

**Comment by sumnerboy12** [comment]
Yes - understand it would require a change to the LCD lib - just wondering if it is simpler to do this way, rather than add a new method to the LCD API? Perhaps we do both? Add handling to `showTemp()` to hide if `NAN` is passed, and add a `hideTemp()` which just calls `showTemp(NAN)`?

**Comment by moinmoin-sh** [comment]
Sure we can do both. I thought having the `hideTemp() `would be more logical to use from a calling FW / Rack32.
That means you could use `hideTemp()` in the config callback and set the temp value to NAN for subsequent `showTemp()` 

So I'll do both !
